### ISSUE TITLE
blast fails in side-by-side installation.

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jbh-jblast#102]
**stand-alone blast**

debug: cmd node /home/centos/jbserver/workflows/Sim.blast.workflow.js --in /home/centos/jbrowse//sample_data/json/volvox/jblastdata/blast_region1519464168153.fa --ext blastxml --out /home/centos/jbrowse/sample_data/json/volvox/jblastdata --profile /home/centos/jbserver/tmp/blast_option1519464168153.json
Starting Sim_Blast.workflow
cp: cannot create regular file ‘/var/www/html/3jbserver/node_modules/jbrowse/sample_data/json/volvox/jblastdata/1519464173460.blastxml’: No such file or directory
Blast Command: cp ./workflows/blastn-sample-with-hits.blastxml /var/www/html/3jbserver/node_modules/jbrowse/sample_data/json/volvox/jblastdata/1519464173460.blastxml
workflowResults: {
    "type": "blastn",
    "outputDirectory": "/var/www/html/3jbserver/node_modules/jbrowse/sample_data/json/volvox/jblastdata",
    "rawOutput": false,
    "db": "/var/www/html/blastdb/htgs/13apr2014/htgs",
    "outfmt": 5,
    "outFileExt": "blastxml",
    "returnParams": true,
    "out": "/var/www/html/3jbserver/node_modules/jbrowse/sample_data/json/volvox/jblastdata/1519464173460.blastxml"
}
Script output [[[[ Starting Sim_Blast.workflow
Blast Command: cp ./workflows/blastn-sample-with-hits.blastxml /var/www/html/3jbserver/node_modules/jbrowse/sample_data/json/volvox/jblastdata/1519464173460.blastxml
workflowResults: {
    "type": "blastn",
    "outputDirectory": "/var/www/html/3jbserver/node_modules/jbrowse/sample_data/json/volvox/jblastdata",
    "rawOutput": false,
    "db": "/var/www/html/blastdb/htgs/13apr2014/htgs",
    "outfmt": 5,
    "outFileExt": "blastxml",
    "returnParams": true,
    "out": "/var/www/html/3jbserver/node_modules/jbrowse/sample_data/json/volvox/jblastdata/1519464173460.blastxml"
}
 ]]]]
debug: mv /var/www/html/3jbserver/node_modules/jbrowse/sample_data/json/volvox/jblastdata/1519464173460.blastxml /var/www/html/3jbserver/node_modules/jbrowse/sample_data/json/volvox/jblastdata/5_1519464173704.blastxml
mv: cannot stat ‘/var/www/html/3jbserver/node_modules/jbrowse/sample_data/json/volvox/jblastdata/1519464173460.blastxml’: No such file or directory
debug: converting blast to json
debug: blastxml2json /home/centos/jbrowse/sample_data/json/volvox/jblastdata/5_1519464173704.blastxml /home/centos/jbrowse/sample_data/json/volvox/jblastdata/5_1519464173704.json
error: Error: ENOENT: no such file or directory, open '/home/centos/jbrowse/sample_data/json/volvox/jblastdata/5_1519464173704.blastxml'
    at Error (native)
error: undefined

**Comment by enuggetry** [comment]
gcaggt\ncgactctagaggatctggctgggtcatttattgtcctgagcacccaagaagatggccaaatt\ngtgggagatgactgagtagaccaggactctttggggaaaggccagaacctagggtcatctgg\naaggtgttaggctagatcaacccctagacatttctacaccccctcaccacacaacacaacca\ncacccccaagcagtagttatataattattcagtatacaaattgtttatttaatgtctatgtt\nagtcagagttctcaaaagaaacaacttatagga',
  workflow: 'NCBI.blast.workflow.js' }
debug: >>> kue push event enqueue 6 workflow
debug: >>> process job event 6 enqueue workflow
info: service process starting: jblast job 6
info: basicWorkflowService beginProcessing[object Object]
blastPath /home/centos/jbrowse//sample_data/json/volvox/jblastdata
debug: sJob created 6
debug: >>> process job event create completed
debug: >>> kue push event start 6 workflow
debug: >>> process job event 6 start workflow
debug: >>> kue push event progress 6 0
debug: >>> kue push event failed 6 faild to write blastOptionFile
debug: >>> process job event update completed
debug: >>> process job event 6 progress 0
debug: >>> process job event update completed
debug: >>> process job event 6 failed faild to write blastOptionFile
debug: >>> process job event update completed
debug: >>> Executing workflow /home/centos/jbserver/workflows/NCBI.blast.workflow.js
debug: cmd node /home/centos/jbserver/workflows/NCBI.blast.workflow.js --in /home/centos/jbrowse//sample_data/json/volvox/jblastdata/blast_region1519464826680.fa --ext blastxml --out /home/centos/jbrowse/sample_data/json/volvox/jblastdata --profile /home/centos/jbserver/tmp/blast_option1519464826680.json
Starting NCBI_Blast.workflow
{ Error: ENOENT: no such file or directory, open '/home/centos/jbserver/tmp/blast_option1519464826680.json'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.readFileSync (fs.js:510:33)
    at Object.<anonymous> (/home/centos/jbserver/workflows/NCBI.blast.workflow.js:47:18)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/centos/jbserver/tmp/blast_option1519464826680.json' }
Script Exit code: 1 number
Script Program stderr:
Script output [[[[ Starting NCBI_Blast.workflow
{ Error: ENOENT: no such file or directory, open '/home/centos/jbserver/tmp/blast_option1519464826680.json'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.readFileSync (fs.js:510:33)
    at Object.<anonymous> (/home/centos/jbserver/workflows/NCBI.blast.workflow.js:47:18)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/centos/jbserver/tmp/blast_option1519464826680.json' }
 ]]]]
error: failed to find workflow results
workflowResults: {
    "type": "blastn",
    "outputDirectory": "/var/www/html/3jbserver/node_modules/jbrowse/sample_data/json/volvox/jblastdata",
    "rawOutput": false,
    "db": "/var/www/html/blastdb/htgs/13apr2014/htgs",
    "outfmt": 5,
    "outFileExt": "blastxml",
    "returnParams": true,
    "out": "/var/www/html/3jbserver/node_modules/jbrowse/sample_data/json/volvox/jblastdata/1519464173460.blastxml"
}
 ]]]]
debug: mv /var/www/html/3jbserver/node_modules/jbrowse/sample_data/json/volvox/jblastdata/1519464173460.blastxml /var/www/html/3jbserver/node_modules/jbrowse/sample_data/json/volvox/jblastdata/5_1519464173704.blastxml
mv: cannot stat ‘/var/www/html/3jbserver/node_modules/jbrowse/sample_data/json/volvox/jblastdata/1519464173460.blastxml’: No such file or directory
debug: converting blast to json
debug: blastxml2json /home/centos/jbrowse/sample_data/json/volvox/jblastdata/5_1519464173704.blastxml /home/centos/jbrowse/sample_data/json/volvox/jblastdata/5_1519464173704.json
error: Error: ENOENT: no such file or directory, open '/home/centos/jbrowse/sample_data/json/volvox/jblastdata/5_1519464173704.blastxml'
    at Error (native)
error: undefined
